# Generated by Django 5.2.1 on 2025-05-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('input_testcase', models.TextField()),
                ('output_testcase', models.TextField()),
                ('testcase_explanation', models.TextField()),
                ('isSolved', models.BooleanField(default=False)),
                ('topic', models.CharField(max_length=50)),
                ('constraints', models.TextField()),
            ],
        ),
    ]
