# Generated by Django 5.2.1 on 2025-06-09 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='isSolved',
        ),
        migrations.AddField(
            model_name='problem',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
